AWSTemplateFormatVersion: "2010-09-09"
  
Parameters:
  Domain:
    Type: String
    Description: 'The root domain name'
    Default: 'eastcodersbank.com'
  
Resources:
  PortalDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultRootObject: 'index.html'
        Comment: 'Portal distribution for admin portal environment.'
        Enabled: true
        DefaultCacheBehavior:
          TargetOriginId: '{{resolve:secretsmanager:AdminBucket:SecretString}}'
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
    
        CustomErrorResponses:
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: '/index.html'
            ErrorCachingMinTTL: 300
        PriceClass: PriceClass_100
        Aliases:
          - !Sub 'admin.${Domain}'
        ViewerCertificate:
          AcmCertificateArn: arn:aws:acm:us-east-2:326848027964:certificate/4215e5dc-ac62-40a8-be74-ca7fdbee2309
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021
        Origins:
          - DomainName: '{{resolve:secretsmanager:AdminBucketDomain:SecretString}}'
            Id: '{{resolve:secretsmanager:AdminBucket:SecretString}}'
            S3OriginConfig:
              OriginAccessIdentity: ''
  PortalDNS:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: '{{resolve:secretsmanager:HostedZone:SecretString}}'
      Comment: 'Public admin portal DNS for angular app'
      RecordSets:
        - Name: !Sub 'admin.${Domain}'
          Type: A
          AliasTarget:
            DNSName: !GetAtt PortalDistribution.DomainName
            HostedZoneId: '{{resolve:secretmanager:HostedZone:SecretString}}'